# Generated by Django 3.2.9 on 2021-11-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20211102_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
